/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CodeInjector: typeof import('./components/CodeInjector.vue')['default']
    GlobalBackground: typeof import('./components/GlobalBackground.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NModal: typeof import('naive-ui')['NModal']
    NoticeBell: typeof import('./components/NoticeBell.vue')['default']
    NPagination: typeof import('naive-ui')['NPagination']
    PendingOrderBanner: typeof import('./components/PendingOrderBanner.vue')['default']
    PendingTicketBanner: typeof import('./components/PendingTicketBanner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StellarDropdown: typeof import('./components/StellarDropdown.vue')['default']
    StellarIcon: typeof import('./components/StellarIcon.vue')['default']
    SubscribeImportModal: typeof import('./components/SubscribeImportModal.vue')['default']
  }
}
